/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacao;

import java.awt.BorderLayout;

/**
 *
 * @author gabriel.girardi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        Pag1 p1 = new Pag1();
        p1.setSize(420,300);
        p1.setLocation(0,0);
        Painel.removeAll();
        Painel.add(p1, BorderLayout.CENTER);
        Painel.revalidate();
        Painel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pag1 = new javax.swing.JButton();
        Pag2 = new javax.swing.JButton();
        Pag3 = new javax.swing.JButton();
        Painel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pag1.setText("Pag1");
        Pag1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pag1ActionPerformed(evt);
            }
        });

        Pag2.setText("Pag2");
        Pag2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pag2ActionPerformed(evt);
            }
        });

        Pag3.setText("Pag3");
        Pag3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pag3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelLayout = new javax.swing.GroupLayout(Painel);
        Painel.setLayout(PainelLayout);
        PainelLayout.setHorizontalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );
        PainelLayout.setVerticalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pag1)
                    .addComponent(Pag3)
                    .addComponent(Pag2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Pag1)
                .addGap(27, 27, 27)
                .addComponent(Pag2)
                .addGap(28, 28, 28)
                .addComponent(Pag3)
                .addContainerGap(261, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pag1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pag1ActionPerformed
        Pag1 P1 = new Pag1();
        P1.setSize(420,420);
        P1.setLocation(0,0);
        Painel.removeAll();
        Painel.add(P1, BorderLayout.CENTER);
        Painel.revalidate();
        Painel.repaint();
    }//GEN-LAST:event_Pag1ActionPerformed

    private void Pag2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pag2ActionPerformed
         Pag2 P2 = new Pag2();
        P2.setSize(420,400);
        P2.setLocation(0,0);
        Painel.removeAll();
        Painel.add(P2, BorderLayout.CENTER);
        Painel.revalidate();
        Painel.repaint();
    }//GEN-LAST:event_Pag2ActionPerformed

    private void Pag3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pag3ActionPerformed
         Pag3 P3 = new Pag3();
        P3.setSize(420,400);
        P3.setLocation(0,0);
        Painel.removeAll();
        Painel.add(P3, BorderLayout.CENTER);
        Painel.revalidate();
        Painel.repaint();
    }//GEN-LAST:event_Pag3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pag1;
    private javax.swing.JButton Pag2;
    private javax.swing.JButton Pag3;
    private javax.swing.JPanel Painel;
    // End of variables declaration//GEN-END:variables
}
